app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from flask_login import UserMixin
from . import db, login_manager
from sqlalchemy.orm import relationship



class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    is_admin = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        return AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True

    def __repr__(self):
        return '<User %r>' % self.username


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))






# # Define the UserRoles DataModel
# class UserRoles(db.Model):
#     id = db.Column(db.Integer(), primary_key=True)
#     user_id = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='CASCADE'))
#     role_id = db.Column(db.Integer(), db.ForeignKey('roles.id', ondelete='CASCADE'))

app/__init__.py
import os
from flask import Flask, url_for
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flaskext.mysql import MySQL





mysql = MySQL()
db = SQLAlchemy()
mail = Mail()
bootstrap = Bootstrap()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)


    db.init_app(app)
    # db.Model.metadata.reflect(db.engine)
    mysql.init_app(app)

    mail.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    # with app.app_context():
    #     db.Model.metadata.reflect(db.engine)


    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='/register/admin')

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/register/admin/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from . import main
from ..models import db
from .. import mysql
from flask import render_template
from flask_login import login_required , current_user

@main.route('/')
def index():
    return render_template('index.html')


@main.route('/students')
@login_required
def students():
    return render_template('dashboard.html')


@main.route('/students/<id>')
@login_required
def student(id):
    pass

@main.route('/uhd/<id>')
def uhd(id):
    cur = mysql.get_db().cursor()
    cur.execute('''SELECT * FROM USER WHERE ID = %s''' % id)
    rv = cur.fetchall()
    return str(rv[0][2])

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock%}</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/materialize.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <div class="container">

        <nav>
            <ul id="dropdown1" class="dropdown-content">
                <li ><a href="{{ url_for('auth.change_password') }}"><i class="material-icons">settings</i>password</a></li>
                <li><a href="{{ url_for('auth.change_email') }}">Change email</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('auth.logout') }}">(Sign Out)</a></li>
            </ul>
            <div class="nav-wrapper teal darken-2">
                <a href="{{ url_for('main.index') }}" class="brand-logo center">UHD</a>
                <ul class="left hide-on-med-and-down">
                    {% if current_user.is_authenticated and current_user.is_admin %}
                    <li><a href="{{ url_for('auth.register') }}">Register a user</a></li>
                    {% endif %}

                    {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.students') }}">Students</a></li>
                    {% endif %}

                </ul>
                <ul class="right">
                    {% if current_user.is_authenticated %}
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{ current_user.username }}<i class="material-icons right">arrow_drop_down</i></a></li>
                    {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Sign In</a></li>
                    {% endif %}
                </ul>

            </div>
        </nav>

        {% block content %}



        {% endblock %}

        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>

        <script type="text/javascript">
            $(".dropdown-button").dropdown();
        </script>

        {% block javascript %}

        {% endblock %}
    </div>

</body>

</html>

app/templates/dashboard.html
{% extends "base.html" %}

{% block title%}
UHD -Students
{% endblock %}

{% block content %}



<div class="row">

    <div class="col s12">

        <table class="striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Item Name</th>
                    <th>Item Price</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>Alvin</td>
                    <td>Eclair</td>
                    <td>$0.87</td>
                </tr>
                <tr>
                    <td>Alan</td>
                    <td>Jellybean</td>
                    <td>$3.76</td>
                </tr>
                <tr>
                    <td>Jonathan</td>
                    <td>Lollipop</td>
                    <td>$7.00</td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- col s9 -->
</div>
<!-- row -->


<ul class="pagination">
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    <li class="active"><a href="#!">1</a></li>
    <li class="waves-effect"><a href="#!">2</a></li>
    <li class="waves-effect"><a href="#!">3</a></li>
    <li class="waves-effect"><a href="#!">4</a></li>
    <li class="waves-effect"><a href="#!">5</a></li>
    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
</ul>



{% endblock %}

{% block javascript %}
    <script type="text/javascript">
            {% for message in get_flashed_messages() %}
            var $toastContent = $('<span>{{ message }} </span>').add($('<i class="material-icons"></i>'));
                Materialize.toast($toastContent, 10000);
            {% endfor %}
    </script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title%}
UHD
{% endblock %}

{% block content %}
<div class="intro blue-grey darken-3 z-depth-1">
    <h1 class="grey-text text-lighten-5">Freshmen Admin Portal </h1>
    <h5 clas="grey lighten-4 grey-text text-darken-1">University of Human Development</h5>
</div>

<div class="container about">
    <h5> Please sign in to see the dashboard</h5>
    <h6><a href="{{ url_for('auth.login') }}">Sign In</a></h6>
    <hr>
    <div class="row">
        <div class="col s12 m4 l4">
            <h6>Story</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
        <div class="col s12 m4 l4">
            <h6>Profile</h6>
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <!-- <img src="http://labs.qnimate.com/portfolio-materialize/images/profile.png" width="64" height="64"> -->
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
                </div>
                <div class="card-action">
                    <a href="#">Link</a>
                    <a href='#'>Link</a>
                </div>
            </div>
        </div>
        <div class="col s12 m4 l4">
            <h6>current jobs</h6>
            <ul class="collapsible">
                <li class="active">
                    <div class="collapsible-header"><i class="mdi-av-web"></i>Designer</div>
                    <div class="collapsible-body">
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header"><i class="mdi-editor-format-align-justify"></i>Developer</div>
                    <div class="collapsible-body">
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header"><i class="mdi-av-play-shopping-bag"></i>Video Editor</div>
                    <div class="collapsible-body">
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header"><i class="mdi-editor-insert-comment"></i>Support Asst.</div>
                    <div class="collapsible-body">
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="container portfolio">
    <h5>International Scientific Conference</h5>
    <h6>
</h6>
    <hr>
    <div class="row">
        <div class="col s12 m12 l12 portfolio-holder">
            <!-- <img class="materialboxed" src="http://uhd.edu.iq/img/image/albums/inte_conference_4/uhd_40.jpg">
            <img class="materialboxed" src="http://uhd.edu.iq/img/image/albums/International_Conference/10.JPG">
            <img class="materialboxed" src="http://uhd.edu.iq/img/image/albums/International_Conference/2.JPG">
            <img class="materialboxed" src="http://uhd.edu.iq/img/image/albums/International_Conference/49.JPG">
            <img class="materialboxed" src="http://uhd.edu.iq/img/image/albums/inte_conference_4/uhd_63.jpg">
            <img class="materialboxed" src="http://uhd.edu.iq/img/image/albums/inte_conference_4/uhd_104.jpg"> -->
        </div>
    </div>
</div>

<footer>
    <div class="footer-copyright">
        <div class="container center">
            © 2017 Copyright Text
            <a class="grey-text text-lighten-4 right" href="/">Link</a>
        </div>
    </div>
</footer>


{% endblock %}

{% block javascript %}
<script type="text/javascript">
    {% for message in get_flashed_messages() %}

    var $toastContent = $('<span>{{ message }} </span>').add($('<i class="material-icons"></i>'));
    Materialize.toast($toastContent, 10000);

    {% endfor %}

    $(document).ready(function() {
        $('.materialboxed').materialbox();
    });
    $(document).ready(function() {
        $('.materialboxed').materialbox();
    });
</script>
{% endblock %}